using System.Text.Json.Serialization;

namespace Telescope.Model;

public class PowerBiReport
{
    /// <summary>
    /// Unique autogenerated id
    /// </summary>
    [JsonPropertyName("id")]
    public int Id { get; set; }

    /// <summary>
    /// Unique name given to the report
    /// </summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = null!;

    /// <summary>
    /// Free-format description given to the report
    /// </summary>
    [JsonPropertyName("description")]
    public string Description { get; set; } = null!;

    /// <summary>
    /// False means cross all depots.  True means filtered by Depot
    /// </summary>
    [JsonPropertyName("depotSpecific")]
    public bool DepotSpecific { get; set; }

    /// <summary>
    /// Used to select the correct report icon.  Charger, Vehicle etc
    /// </summary>
    [JsonPropertyName("category")]
    public string Category { get; set; } = null!;
}